In [2]:

import pandas as pd

In [3]:
score = [['홍길동', 100, 90, 80],
        ['정약용', 80, 90, 100],
        ['규리', 10, 20, 30]]
score_df = pd.DataFrame(score, columns=['이름', '국어', '영어', '수학'])
score_df

    이름   국어  영어   수학
0  홍길동  100  90   80
1  정약용   80  90  100
2   규리   10  20   30

In [ ]:
score_df.drop(['국어'], axis=1)

Empty DataFrame
Columns: [이름, 국어, 영어, 수학]
Index: []

In [7]:
score_df.drop([1], inplace=True)